"use strict";
// Copyright 2017-2022 @polkadot/apps-config authors & contributors
// SPDX-License-Identifier: Apache-2.0
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
exports.__esModule = true;
var acala_1 = require("./acala");
var ajuna_1 = require("./ajuna");
var altair_1 = require("./altair");
var apron_1 = require("./apron");
var ares_gladios_1 = require("./ares-gladios");
var ares_parachain_1 = require("./ares-parachain");
var astar_1 = require("./astar");
var automata_1 = require("./automata");
var basilisk_1 = require("./basilisk");
var beresheet_1 = require("./beresheet");
var bifrost_1 = require("./bifrost");
var bifrost_asgard_1 = require("./bifrost-asgard");
var bifrost_parachain_1 = require("./bifrost-parachain");
var bitcountry_1 = require("./bitcountry");
var bitcountry_pioneer_1 = require("./bitcountry-pioneer");
var bitcountry_rococo_1 = require("./bitcountry-rococo");
var canvas_1 = require("./canvas");
var centrifuge_1 = require("./centrifuge");
var centrifuge_chain_1 = require("./centrifuge-chain");
var chainx_1 = require("./chainx");
var clover_1 = require("./clover");
var clover_rococo_1 = require("./clover-rococo");
var coinversation_1 = require("./coinversation");
var competitors_club_1 = require("./competitors-club");
var crab_1 = require("./crab");
var crown_sterling_1 = require("./crown-sterling");
var crust_1 = require("./crust");
var cumulus_test_parachain_1 = require("./cumulus-test-parachain");
var darwinia_1 = require("./darwinia");
var datahighway_1 = require("./datahighway");
var dock_mainnet_1 = require("./dock-mainnet");
var dock_testnet_1 = require("./dock-testnet");
var dotmog_1 = require("./dotmog");
var eave_1 = require("./eave");
var edgeware_1 = require("./edgeware");
var encointer_node_notee_1 = require("./encointer-node-notee");
var encointer_node_teeproxy_1 = require("./encointer-node-teeproxy");
var encointer_para_1 = require("./encointer-para");
var equilibrium_1 = require("./equilibrium");
var fantour_1 = require("./fantour");
var galital_1 = require("./galital");
var galital_parachain_1 = require("./galital-parachain");
var galois_1 = require("./galois");
var gamepower_1 = require("./gamepower");
var genshiro_1 = require("./genshiro");
var hanonycash_1 = require("./hanonycash");
var hydrate_1 = require("./hydrate");
var idavoll_1 = require("./idavoll");
var integritee_1 = require("./integritee");
var interbtc_1 = require("./interbtc");
var ipse_1 = require("./ipse");
var jupiter_1 = require("./jupiter");
var jupiter_rococo_1 = require("./jupiter-rococo");
var khala_1 = require("./khala");
var kilt_1 = require("./kilt");
var konomi_1 = require("./konomi");
var kpron_1 = require("./kpron");
var kulupu_1 = require("./kulupu");
var kusari_1 = require("./kusari");
var kylin_1 = require("./kylin");
var laminar_1 = require("./laminar");
var litentry_1 = require("./litentry");
var mangata_1 = require("./mangata");
var manta_1 = require("./manta");
var mathchain_1 = require("./mathchain");
var moonbeam_1 = require("./moonbeam");
var mybank_1 = require("./mybank");
var neatcoin_1 = require("./neatcoin");
var neumann_1 = require("./neumann");
var nftmart_1 = require("./nftmart");
var nodle_1 = require("./nodle");
var opal_1 = require("./opal");
var opportunity_1 = require("./opportunity");
var origintrail_1 = require("./origintrail");
var pangolin_1 = require("./pangolin");
var pangoro_1 = require("./pangoro");
var parallel_1 = require("./parallel");
var parami_1 = require("./parami");
var phoenix_1 = require("./phoenix");
var pichiu_1 = require("./pichiu");
var plasm_1 = require("./plasm");
var polkadex_1 = require("./polkadex");
var polkafoundry_1 = require("./polkafoundry");
var polymesh_1 = require("./polymesh");
var pontem_1 = require("./pontem");
var prism_1 = require("./prism");
var quartz_1 = require("./quartz");
var realis_1 = require("./realis");
var riochain_1 = require("./riochain");
var robonomics_1 = require("./robonomics");
var shibuya_1 = require("./shibuya");
var shiden_1 = require("./shiden");
var snowbridge_1 = require("./snowbridge");
var soraSubstrate_1 = require("./soraSubstrate");
var spanner_1 = require("./spanner");
var stafi_1 = require("./stafi");
var standard_1 = require("./standard");
var subdao_1 = require("./subdao");
var subgame_1 = require("./subgame");
var subsocial_1 = require("./subsocial");
// import subspace from './subspace';
var substrateContractsNode_1 = require("./substrateContractsNode");
var swapdex_1 = require("./swapdex");
var ternoa_1 = require("./ternoa");
var trustbase_1 = require("./trustbase");
var uart_1 = require("./uart");
var unique_1 = require("./unique");
var unitv_1 = require("./unitv");
var vln_1 = require("./vln");
var vln_rococo_1 = require("./vln-rococo");
var vodka_1 = require("./vodka");
var web3games_1 = require("./web3games");
var westlake_1 = require("./westlake");
var zCloak_1 = require("./zCloak");
var zeitgeist_1 = require("./zeitgeist");
var zenlink_1 = require("./zenlink");
var zero_1 = require("./zero");
// NOTE: The mapping is done from specName in state.getRuntimeVersion
var spec = __assign(__assign({ Crab: crab_1["default"], Darwinia: darwinia_1["default"], 'Darwinia Crab PC2': pangolin_1["default"], 'Darwinia PC2': pangolin_1["default"], Equilibrium: equilibrium_1["default"], Genshiro: genshiro_1["default"], Pangolin: pangolin_1["default"], Pangoro: pangoro_1["default"], VLN: vln_1["default"], 'VLN-PC': vln_rococo_1["default"] }, acala_1["default"]), { ajuna: ajuna_1["default"], altair: altair_1["default"], apron: apron_1["default"], 'ares-gladios': ares_gladios_1["default"], 'ares-mars': ares_parachain_1["default"], 'ares-odyssey': ares_parachain_1["default"], asgard: bifrost_asgard_1["default"], astar: astar_1["default"], automata: automata_1["default"], basilisk: basilisk_1["default"], beresheet: beresheet_1["default"], bifrost: bifrost_1["default"], 'bifrost-parachain': bifrost_parachain_1["default"], 'bitcountry-node': bitcountry_1["default"], 'bitcountry-parachain': bitcountry_rococo_1["default"], canvas: canvas_1["default"], centrifuge: centrifuge_1["default"], 'centrifuge-chain': centrifuge_chain_1["default"], chainx: chainx_1["default"], 'chainx-parachain': chainx_1["default"], clover: clover_1["default"], 'clover-rococo': clover_rococo_1["default"], coinversation: coinversation_1["default"], 'competitors-club': competitors_club_1["default"], contextfree: automata_1["default"], 'crown-sterling': crown_sterling_1["default"], crust: crust_1["default"], 'crust-parachain': crust_1["default"], 'cumulus-subsocial-parachain': subsocial_1["default"], 'cumulus-test-parachain': cumulus_test_parachain_1["default"], datahighway: westlake_1["default"], 'datahighway-parachain': datahighway_1["default"], dawn: eave_1["default"], 'dev-parachain': zenlink_1["default"], 'dock-pos-main-runtime': dock_mainnet_1["default"], 'dock-pos-test-runtime': dock_testnet_1["default"], 'dotmog-node': dotmog_1["default"], edgeware: edgeware_1["default"], 'encointer-node-notee': encointer_node_notee_1["default"], 'encointer-node-teeproxy': encointer_node_teeproxy_1["default"], 'encointer-parachain': encointer_para_1["default"], fantour: fantour_1["default"], galital: galital_1["default"], 'galital-collator': galital_parachain_1["default"], gamepower: gamepower_1["default"], 'hack-hydra-dx': hydrate_1["default"], halongbay: polkafoundry_1["default"], hanonycash: hanonycash_1["default"], heiko: parallel_1["default"], 'hydra-dx': hydrate_1["default"], idavoll: idavoll_1["default"], 'integritee-parachain': integritee_1["default"], 'interbtc-parachain': interbtc_1["default"], 'interbtc-standalone': interbtc_1["default"], 'ipse-node': ipse_1["default"], 'jupiter-prep': jupiter_1["default"], 'jupiter-rococo': jupiter_rococo_1["default"], khala: khala_1["default"], 'kilt-parachain': kilt_1["default"], 'kilt-spiritnet': kilt_1["default"], 'kintsugi-parachain': interbtc_1["default"], konomi: konomi_1["default"], kpron: kpron_1["default"], kulupu: kulupu_1["default"], kusari: kusari_1["default"], kylin: kylin_1["default"], laminar: laminar_1["default"], litentry: litentry_1["default"], mangata: mangata_1["default"], 'manta-node': manta_1["default"], 'mashnet-node': kilt_1["default"], mathchain: mathchain_1["default"], 'mathchain-galois': galois_1["default"], moonbase: moonbeam_1["default"], moonbeam: moonbeam_1["default"], moonriver: moonbeam_1["default"], moonshadow: moonbeam_1["default"], 'mybank.network Testnet': mybank_1["default"], neatcoin: neatcoin_1["default"], neumann: neumann_1["default"], nft: unique_1["default"], nftmart: nftmart_1["default"], 'node-moonbeam': moonbeam_1["default"], 'node-polkadex': polkadex_1["default"], 'nodle-chain': nodle_1["default"], opal: opal_1["default"], opportunity: opportunity_1["default"], 'origintrail-parachain': origintrail_1["default"], parallel: parallel_1["default"], parami: parami_1["default"], 'phoenix-node': phoenix_1["default"], 'phoenix-parachain': phoenix_1["default"], pichiu: pichiu_1["default"], 'pioneer-runtime': bitcountry_pioneer_1["default"], plasm: plasm_1["default"], polymesh: polymesh_1["default"], 'pontem-node': pontem_1["default"], prism: prism_1["default"], quartz: quartz_1["default"], realis: realis_1["default"], 'riochain-runtime': riochain_1["default"], robonomics: robonomics_1["default"], shibuya: shibuya_1["default"], shiden: shiden_1["default"], snowbridge: snowbridge_1["default"], 'sora-substrate': soraSubstrate_1["default"], sora_ksm: soraSubstrate_1["default"], spanner: spanner_1["default"], stafi: stafi_1["default"], standard: standard_1["default"], steam: eave_1["default"], subdao: subdao_1["default"], subgame: subgame_1["default"], subsocial: subsocial_1["default"], 
    // subspace,
    'substrate-contracts-node': substrateContractsNode_1["default"], subzero: zero_1["default"], swapdex: swapdex_1["default"], ternoa: ternoa_1["default"], trustbase: trustbase_1["default"], uart: uart_1["default"], 'unit-node': unitv_1["default"], 'unit-parachain': unitv_1["default"], unorthodox: standard_1["default"], vodka: vodka_1["default"], 'web3games-node': web3games_1["default"], 'zcloak-network': zCloak_1["default"], zeitgeist: zeitgeist_1["default"] });
exports["default"] = spec;
