"use strict";
// Copyright 2017-2022 @subwallet/utils authors & contributors
// SPDX-License-Identifier: Apache-2.0
exports.__esModule = true;
// Do not edit, auto-generated by @polkadot/dev
var util_1 = require("@polkadot/util");
var detectOther_1 = require("./detectOther");
var packageInfo_1 = require("./packageInfo");
(0, util_1.detectPackage)(packageInfo_1.packageInfo, null, detectOther_1["default"]);
