"use strict";
// Copyright 2017-2022 @subwallet/utils authors & contributors
// SPDX-License-Identifier: Apache-2.0
exports.__esModule = true;
// Empty template, auto-generated by @polkadot/dev
exports["default"] = [];
