// Copyright 2017-2023 @subwallet/chain-list authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@subwallet/chain-list', path: 'auto', type: 'auto', version: '0.2.29-beta.0' };
