"use strict";
// Copyright 2017-2022 @subwallet/utils authors & contributors
// SPDX-License-Identifier: Apache-2.0
exports.__esModule = true;
exports.packageInfo = void 0;
// Do not edit, auto-generated by @polkadot/dev
exports.packageInfo = { name: '@subwallet/utils', path: 'auto', type: 'auto', version: '0.0.1' };
